### ISSUE TITLE
Replace object-assign with object.defaults or object.assign

### ISSUE THREAD

**Issue by phated** [sttk/each-props#1]
Hey @sttk, I'm trying to dedupe the gulp dependency tree and I found `object-assign` in the tree.  Could you replace it with `object.defaults` or `object.assign`?  I'd prefer `object.defaults` because I help maintain it.

**Comment by sttk** [comment]
@phated Oh, `object-assign` was deprecated. Thank you for informing me of that.
I'll modify to use `object.defaults` as you said.

**Comment by sttk** [comment]
@phated I've modified and released 1.3.1.  Thanks!

**Comment by phated** [comment]
@sttk awesome! thanks!
